### ISSUE TITLE
comands (ctrl+shift+p) are disabled on break

### ISSUE THREAD

**Issue by AsaAyers** [lsewilson/PomPomodoro#40]
I can open the prompt, but I can't type anything. I had to use the menu commands to skip the break.

**Comment by lsewilson** [comment]
@AsaAyers - we programmed the break so that keyboard is disabled intentionally. Our aim was to discourage users from continuing with their work and to actually enforce a break. Is your issue the fact that atom still responds to hotkeys while on a break? Or are you suggesting we implement a hotkey shortcut for skipping the break?

**Comment by AsaAyers** [comment]
ok, I think the issue is that this plugin isn't for me, and I wasn't sure how the break was actually going to work. I just saw your announcement in the Atom slack and figured I'd try it out. I'm familiar with the idea of Pomodoro, but I've never succeeded in implementing that technique as I work.

I believe the editor was still working when it tried to enforce the break, so this seemed like a bug. I use vim-mode, so I rarely use the mouse in Atom.
